version: 2
jobs:
  build:
    docker:
      - image: continuul/build-essential:latest

    steps:
      - checkout

      - run:
          name: Build
          command: make -B
          command: make memtest
          command: make test