version: 2
jobs:
  build:
    docker:
      - image: continuul/build-essential:latest

    steps:
      - checkout

      - run:
          name: Build
          command: make -B

      - run:
          name: Memory
          command: make memtest -B


      - run:
          name: Test
          command: make test -B